use serde_json::{Value as Json, json};

pub const CAPABILITIES: &[&str] = &[
    "SELECTLIST_PROJECTION",
    "SELECTLIST_EXPRESSIONS",
    "FILTER_EXPRESSIONS",
    "LITERAL_BOOL",
    "LITERAL_DATE",
    "LITERAL_DOUBLE",
    "LITERAL_EXACTNUMERIC",
    "LITERAL_NULL",
    "LITERAL_STRING",
    "LITERAL_TIMESTAMP",
    "LITERAL_TIMESTAMP_UTC",
    "FN_PRED_AND",
    "FN_PRED_OR",
    "FN_PRED_NOT",
    // Exasol normalises `a > b` to `b < a`; there is no FN_PRED_GREATER capability.
    "FN_PRED_EQUAL",
    "FN_PRED_NOTEQUAL",
    "FN_PRED_LESS",
    "FN_PRED_LESSEQUAL",
    "FN_PRED_BETWEEN",
    "FN_PRED_IN_CONSTLIST",
    "FN_PRED_IS_NULL",
    "FN_PRED_IS_NOT_NULL",
    "FN_PRED_LIKE",
    "FN_PRED_LIKE_ESCAPE",
    "FN_PRED_REGEXP_LIKE",
    "LIMIT",
    // The per-shard bounded top-N never carries an offset: a non-zero offset
    // declines that path to the row-scan wrapper.
    "ORDER_BY_COLUMN",
    "ORDER_BY_EXPRESSION",
    "LIMIT_WITH_OFFSET",
    "FN_ADD",
    "FN_SUB",
    "FN_MULT",
    "FN_FLOAT_DIV",
    "FN_NEG",
    // A CAST target renderable under neither dialect (INTERVAL/GEOMETRY/HASHTYPE/
    // TIMESTAMP WITH LOCAL TIME ZONE) fails the query.
    "FN_CAST",
    "FN_ABS",
    "FN_ACOS",
    "FN_ASIN",
    "FN_ATAN",
    "FN_ATAN2",
    "FN_CEIL",
    "FN_COS",
    "FN_COSH",
    "FN_COT",
    "FN_DEGREES",
    "FN_EXP",
    "FN_FLOOR",
    "FN_LN",
    "FN_LOG",
    "FN_MOD",
    "FN_POWER",
    "FN_RADIANS",
    "FN_ROUND",
    "FN_SIGN",
    "FN_SIN",
    "FN_SINH",
    "FN_SQRT",
    "FN_TAN",
    "FN_TANH",
    "FN_TRUNC",
    "FN_ASCII",
    "FN_CHR",
    "FN_CONCAT",
    "FN_INITCAP",
    "FN_INSTR",
    "FN_LEFT",
    "FN_LENGTH",
    "FN_LOCATE",
    "FN_LOWER",
    "FN_LPAD",
    "FN_LTRIM",
    "FN_OCTET_LENGTH",
    "FN_REPEAT",
    "FN_REPLACE",
    "FN_REVERSE",
    "FN_RIGHT",
    "FN_RPAD",
    "FN_RTRIM",
    "FN_SUBSTR",
    "FN_TRANSLATE",
    "FN_TRIM",
    "FN_UNICODE",
    "FN_UNICODECHR",
    "FN_UPPER",
    // The now-family (CURRENT_DATE/CURRENT_TIMESTAMP/SYSDATE/SYSTIMESTAMP) is not
    // advertised: the scan UDF sees neither SESSIONTIMEZONE nor DBTIMEZONE and would
    // read its UTC container clock once per shard, while Exasol's is statement-constant.
    "FN_DATE_TRUNC",
    "FN_DAY",
    "FN_EXTRACT",
    "FN_HOUR",
    "FN_MINUTE",
    "FN_MONTH",
    "FN_SECOND",
    "FN_TO_DATE",
    "FN_TO_TIMESTAMP",
    "FN_YEAR",
    "FN_WEEK",
    // ADD_HOURS/ADD_MINUTES are not advertised: Exasol infers TIMESTAMP(0) for
    // ADD_HOURS(DATE, n) but the type-blind rendering yields TIMESTAMP(3), which
    // Exasol rejects.
    "FN_DAYS_BETWEEN",
    "FN_HOURS_BETWEEN",
    "FN_MINUTES_BETWEEN",
    "FN_SECONDS_BETWEEN",
    "FN_CASE",
    "FN_GREATEST",
    "FN_LEAST",
    "FN_NULLIFZERO",
    "FN_ZEROIFNULL",
    "AGGREGATE_SINGLE_GROUP",
    "FN_AGG_COUNT",
    "FN_AGG_COUNT_STAR",
    "FN_AGG_SUM",
    "FN_AGG_MIN",
    "FN_AGG_MAX",
    "FN_AGG_AVG",
    // COUNT(DISTINCT) inside a GROUP BY request falls back to row scanning.
    "FN_AGG_COUNT_DISTINCT",
    "FN_AGG_STDDEV",
    "FN_AGG_STDDEV_POP",
    "FN_AGG_STDDEV_SAMP",
    "FN_AGG_VARIANCE",
    "FN_AGG_VAR_POP",
    "FN_AGG_VAR_SAMP",
    "AGGREGATE_GROUP_BY_COLUMN",
    "AGGREGATE_GROUP_BY_EXPRESSION",
    "AGGREGATE_GROUP_BY_TUPLE",
    "AGGREGATE_HAVING",
    "JOIN",
    "JOIN_TYPE_INNER",
    "JOIN_CONDITION_EQUI",
];

pub fn get_capabilities_response() -> Json {
    json!({
        "type": "getCapabilities",
        "capabilities": CAPABILITIES,
    })
}

#[cfg(test)]
#[path = "capabilities_tests.rs"]
mod tests;
