#!/usr/bin/env bash
# Bring up the Exasol cluster for a named env. Runs c4 FROM THIS MACHINE (jumphost model): c4 must
# not run on a cluster node, because it SSHes to the nodes' external IPs and a node cannot hairpin to
# its own public IP. This machine is in the SG allowlist, so it can reach every node's external IP.
# SLC + .so install is done later by `make bench`.
#
#   AWS_PROFILE=spot-strata-deployer ./cluster-up.sh <env_name>
#
# Requires the EC2 private key locally (RSA PEM). Override its path with KEY_FILE=... (default
# ~/.ssh/<key_pair_name>). c4 resolves CCC_HOST_KEY_PAIR_FILE (a bare name) in ~/.ssh, so the key is
# copied there.
set -euo pipefail

ENV="${1:?usage: cluster-up.sh <env_name>}"
HERE="$(cd "$(dirname "$0")" && pwd)"
STACK="$HERE/../cluster-stack"
C4DIR="$HERE/../.c4"
C4="$C4DIR/c4"
EXASOL_TAG="${EXASOL_IMAGE_TAG:-exasol-2025.2.1}"
# DB memory is NOT pinned: the database auto-starts at the max allowable RAM (per DB architect). c4's
# play template already auto-sizes MemSize from each node's real RAM (via `c4 _ calculate-memory`,
# which leaves headroom for host/COS/UDFs) — but ONLY when CCC_PLAY_DB_MEM_SIZE resolves to empty at
# play time. Two subtleties (verified against c4 4.31.0): (1) c4's built-in DEFAULT for this param is
# 32768 MiB, so simply omitting it from ~/.ccc/config is NOT enough — the default wins and pins 32
# GiB; (2) an empty line *in the config file* is also ignored (default still wins). Only an EMPTY
# ENVIRONMENT override forces the empty resolution that triggers the auto-size branch. So we never
# write the param into the config and instead export CCC_PLAY_DB_MEM_SIZE= for the play (see below).
SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

cd "$STACK"
tofu workspace select "$ENV" >/dev/null 2>&1 || { echo "no workspace '$ENV' (tofu apply first)"; exit 1; }
OUT="$(tofu output -json)"
jqr() { jq -r "$1" <<<"$OUT"; }
mapfile -t INT_IPS < <(jqr '.internal_ips.value[]')
mapfile -t EXT_IPS < <(jqr '.external_ips.value[]')
RESERVE="$(jqr '.reserve_nodes.value')"
KEY_NAME="$(jqr '.key_pair_name.value')"
CL_SSM="$(jqr '.ssm_root.value')"
NODE1="${EXT_IPS[0]}"
KEY_FILE="${KEY_FILE:-$HOME/.ssh/${KEY_NAME}}"

[ -f "$KEY_FILE" ] || { echo "private key not found: $KEY_FILE (set KEY_FILE=...)"; exit 1; }
KEY_BASE="$(basename "$KEY_FILE")"

ssm() { aws ssm get-parameter --with-decryption --name "$1" --query 'Parameter.Value' --output text; }
DB_PASS="$(ssm "$CL_SSM/db_password")"
ADMIN_PASS="$(ssm "$CL_SSM/admin_password")"
BFS_PASS="$(ssm "$CL_SSM/bucketfs_password")"

# c4 looks for the key by bare name in the running user's ~/.ssh.
mkdir -p "$HOME/.ssh"
[ "$KEY_FILE" = "$HOME/.ssh/$KEY_BASE" ] || cp "$KEY_FILE" "$HOME/.ssh/$KEY_BASE"
chmod 600 "$HOME/.ssh/$KEY_BASE"

echo "==> Fetching c4 (local)" >&2
mkdir -p "$C4DIR"
[ -x "$C4" ] || { wget -q https://x-up.s3.amazonaws.com/releases/c4/linux/x86_64/latest/c4 -O "$C4" && chmod +x "$C4"; }

echo "==> Waiting for SSH on all nodes" >&2
for ip in "${EXT_IPS[@]}"; do
  for _ in $(seq 1 30); do
    ssh $SSHOPTS -i "$KEY_FILE" ubuntu@"$ip" true 2>/dev/null && break
    sleep 5
  done
done

echo "==> Rendering ~/.ccc/config (${#INT_IPS[@]} hosts, reserve=$RESERVE, db_mem=auto/max)" >&2
mkdir -p "$HOME/.ccc"
cat >"$HOME/.ccc/config" <<EOF
CCC_HOST_ADDRS="${INT_IPS[*]}"
CCC_HOST_EXTERNAL_ADDRS="${EXT_IPS[*]}"
CCC_HOST_DATADISK=/dev/nvme1n1
CCC_HOST_IMAGE_USER=ubuntu
CCC_HOST_KEY_PAIR_FILE=$KEY_BASE
CCC_PLAY_RESERVE_NODES=${RESERVE}
CCC_PLAY_DB_PASSWORD=${DB_PASS}
CCC_PLAY_ADMIN_PASSWORD=${ADMIN_PASS}
CCC_ADMINUI_START_SERVER=true
CCC_PLAY_WITH_DB=true
EOF

echo "==> Running c4 host play -T @$EXASOL_TAG (several minutes; DB auto-sizes to max RAM)" >&2
# Force c4's auto-max memory sizing: an EMPTY env override for CCC_PLAY_DB_MEM_SIZE resolves to empty
# (unlike an empty config-file line, which the 32768 MiB default overrides). Empty → the play template
# takes its else branch and sets MemSize from each node's real RAM via `c4 _ calculate-memory`, summed
# over the active nodes (total). No DB-memory value is set anywhere in this script or the config.
CCC_PLAY_DB_MEM_SIZE= "$C4" host play -T @"$EXASOL_TAG"

# Ensure the DB is started (auto_start can lag; explicit start is idempotent once MemSize > 0).
echo "==> Starting Exasol DB" >&2
for _ in $(seq 1 12); do ssh $SSHOPTS -p 20002 -i "$KEY_FILE" root@"$NODE1" true 2>/dev/null && break; sleep 10; done
ssh $SSHOPTS -p 20002 -i "$KEY_FILE" root@"$NODE1" "confd_client db_start db_name: Exasol" 2>&1 | head -3 || true

echo "==> Waiting for Exasol DB on $NODE1:8563" >&2
for _ in $(seq 1 60); do
  (exec 3<>"/dev/tcp/$NODE1/8563") 2>/dev/null && { exec 3>&-; echo "   DB port open"; break; }
  sleep 10
done

# The BucketFS write password is generated by c4 and lives (base64) in EXAConf; secrets.sh reads it
# from there for bench. Nothing to set here.

cat <<EOF

Cluster '$ENV' is up.
  c4 (local):   $C4 ps
  DB:           $NODE1:8563   (sys / SSM $CL_SSM/db_password)
  Admin UI:     https://$NODE1:8443

Next:
  ./scripts/secrets.sh $ENV     # writes bench/.env
  make bench                    # builds .so, installs SLC + .so, runs the perf test
EOF
