#!/usr/bin/env bash
# Writes the gitignored bench/.env for remote-mode `make bench`.
#   AWS_PROFILE=spot-strata-deployer ./secrets.sh <env_name>
set -euo pipefail

ENV="${1:?usage: secrets.sh <env_name>}"
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
STACK="$HERE/../cluster-stack"

cd "$STACK"
tofu workspace select "$ENV" >/dev/null 2>&1 || { echo "no workspace '$ENV'"; exit 1; }
# Not `tofu output -json`: that exposes every sensitive output, not just the ones used here.
raw() { local name="$1"; tofu output -raw "$name"; }

NODE1="$(raw first_node_ip)"
CL_SSM="$(raw ssm_root)"
DATA_SSM="$(raw data_ssm_root)"
DB_PORT="$(raw exasol_db_port)"
BFS_PORT="$(raw bucketfs_port)"
KEY_NAME="$(raw key_pair_name)"
KEY_FILE="${KEY_FILE:-$HOME/.ssh/${KEY_NAME}}"
SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

ssm() { aws ssm get-parameter --with-decryption --name "$1" --query 'Parameter.Value' --output text; }

REGION="$(ssm "$DATA_SSM/region")"
GLUE_URI="$(ssm "$DATA_SSM/glue/uri")"
GLUE_WH="$(ssm "$DATA_SSM/glue/warehouse")"
NS_TPCH="$(ssm "$DATA_SSM/namespace/tpch")"
AKID="$(ssm "$DATA_SSM/engine/access_key_id")"
ASEC="$(ssm "$DATA_SSM/engine/secret_access_key")"
DB_PASS="$(ssm "$CL_SSM/db_password")"
# c4 stores the BucketFS write password double-base64 in EXAConf; HTTP basic auth wants it decoded once.
BFS_ENC="$(ssh $SSHOPTS -p 20002 -i "$KEY_FILE" root@"$NODE1" \
  "grep -A18 'BucketFS : bfsdefault' /exa/etc/EXAConf | awk '/WritePasswd/{print \$3; exit}'")"
BFS_PASS="$(printf '%s' "$BFS_ENC" | base64 -d)"

ENVFILE="$REPO/bench/.env"
cat >"$ENVFILE" <<EOF
# Generated by deploy/scripts/secrets.sh for env '$ENV' — do not commit.
BENCH_TARGET=remote
BENCH_PARALLELISM_FACTOR=8

AWS_REGION=$REGION
AWS_ACCESS_KEY_ID=$AKID
AWS_SECRET_ACCESS_KEY=$ASEC
GLUE_CATALOG_URI=$GLUE_URI
GLUE_WAREHOUSE=$GLUE_WH
NAMESPACE=$NS_TPCH

EXASOL_HOST=$NODE1
LH_EXASOL_PORT=$DB_PORT
LH_BUCKETFS_PORT=$BFS_PORT
EXASOL_SYS_PASSWORD=$DB_PASS
BUCKETFS_WRITE_PASS=$BFS_PASS
EOF

chmod 600 "$ENVFILE"

# BENCH_CATALOG is never written, so a stale bench/.env cannot silently switch a run off Glue.
# Private-IP URIs: they are used by the CONNECTION object inside the cluster's VPC.
LK_STACK="$HERE/../lakekeeper-stack"
if (cd "$LK_STACK" && tofu workspace select "$ENV" >/dev/null 2>&1); then
  lk_raw() { local name="$1"; (cd "$LK_STACK" && tofu output -raw "$name"); }
  LK_SSM="$(lk_raw ssm_root)"
  cat >>"$ENVFILE" <<EOF

LAKEKEEPER_CATALOG_URI=$(lk_raw catalog_uri_private)
LAKEKEEPER_TOKEN_URI=$(lk_raw token_uri_private)
LAKEKEEPER_CLIENT_ID=$(lk_raw oidc_client_id)
LAKEKEEPER_CLIENT_SECRET=$(ssm "$LK_SSM/oauth2/client_secret")
LAKEKEEPER_WAREHOUSE=$(lk_raw warehouse_name)
EOF
  echo "Lakekeeper block added to $ENVFILE (private-IP URIs). Set BENCH_CATALOG=lakekeeper to use it."
else
  echo "No lakekeeper-stack workspace '$ENV' — omitting the Lakekeeper block from $ENVFILE (run deploy/scripts/lakekeeper-up.sh $ENV first if you need it)."
fi

echo "Wrote $ENVFILE (EXASOL_HOST=$NODE1, namespace=$NS_TPCH). Run: make bench"
