#!/usr/bin/env bash
# Write bench/.env for `make bench` (remote mode) from cluster-stack outputs + SSM params.
#
#   AWS_PROFILE=spot-strata-deployer ./secrets.sh <env_name>
#
# Pulls engine S3/Glue creds + DB/BucketFS passwords from SSM (the single source of truth) and the
# cluster host/ports from tofu outputs. No secrets are committed; bench/.env is gitignored.
set -euo pipefail

ENV="${1:?usage: secrets.sh <env_name>}"
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
STACK="$HERE/../cluster-stack"

cd "$STACK"
tofu workspace select "$ENV" >/dev/null 2>&1 || { echo "no workspace '$ENV'"; exit 1; }
OUT="$(tofu output -json)"
jqr() { jq -r "$1" <<<"$OUT"; }

NODE1="$(jqr '.first_node_ip.value')"
CL_SSM="$(jqr '.ssm_root.value')"
DATA_SSM="$(jqr '.data_ssm_root.value')"
DB_PORT="$(jqr '.exasol_db_port.value')"
BFS_PORT="$(jqr '.bucketfs_port.value')"
KEY_NAME="$(jqr '.key_pair_name.value')"
KEY_FILE="${KEY_FILE:-$HOME/.ssh/${KEY_NAME}}"
SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

ssm() { aws ssm get-parameter --with-decryption --name "$1" --query 'Parameter.Value' --output text; }

REGION="$(ssm "$DATA_SSM/region")"
GLUE_URI="$(ssm "$DATA_SSM/glue/uri")"
GLUE_WH="$(ssm "$DATA_SSM/glue/warehouse")"
NS_TPCH="$(ssm "$DATA_SSM/namespace/tpch")"
AKID="$(ssm "$DATA_SSM/engine/access_key_id")"
ASEC="$(ssm "$DATA_SSM/engine/secret_access_key")"
DB_PASS="$(ssm "$CL_SSM/db_password")"
# BucketFS write password is generated by c4 and stored double-base64 in EXAConf; the HTTP write
# password (basic-auth 'w:...') is that value decoded once.
BFS_ENC="$(ssh $SSHOPTS -p 20002 -i "$KEY_FILE" root@"$NODE1" \
  "grep -A18 'BucketFS : bfsdefault' /exa/etc/EXAConf | awk '/WritePasswd/{print \$3; exit}'")"
BFS_PASS="$(printf '%s' "$BFS_ENC" | base64 -d)"

ENVFILE="$REPO/bench/.env"
cat >"$ENVFILE" <<EOF
# Generated by deploy/scripts/secrets.sh for env '$ENV' — do not commit.
BENCH_TARGET=remote
BENCH_SLC_VERSION=0.21.0
BENCH_NR_OF_CORES=8
BENCH_PARALLELISM_FACTOR=8

AWS_REGION=$REGION
AWS_ACCESS_KEY_ID=$AKID
AWS_SECRET_ACCESS_KEY=$ASEC
GLUE_CATALOG_URI=$GLUE_URI
GLUE_WAREHOUSE=$GLUE_WH
NAMESPACE=$NS_TPCH

EXASOL_HOST=$NODE1
LH_EXASOL_PORT=$DB_PORT
LH_BUCKETFS_PORT=$BFS_PORT
EXASOL_SYS_PASSWORD=$DB_PASS
BUCKETFS_WRITE_PASS=$BFS_PASS
EOF

chmod 600 "$ENVFILE"

# --- Lakekeeper block (opt-in, ephemeral) -----------------------------------
# Omitted entirely when this env has no applied lakekeeper-stack workspace — an ephemeral
# catalog nobody has `tofu apply`'d yet is not an error, just nothing to add. BENCH_CATALOG is
# NEVER written here, in either branch: it stays the operator's own explicit choice
# (`BENCH_CATALOG=lakekeeper make bench`), so a stale bench/.env can never silently flip a run
# off Glue. Private-IP URIs only — this file is read by `make bench` running from the operator's
# own machine only in the sense that ITS network calls land in the CONNECTION object executed
# INSIDE the Exasol cluster (same VPC as the Lakekeeper box), never from this machine itself.
LK_STACK="$HERE/../lakekeeper-stack"
if LK_OUT="$(cd "$LK_STACK" && tofu workspace select "$ENV" >/dev/null 2>&1 && tofu output -json)"; then
  lk_jqr() { jq -r "$1" <<<"$LK_OUT"; }
  LK_SSM="$(lk_jqr '.ssm_root.value')"
  cat >>"$ENVFILE" <<EOF

LAKEKEEPER_CATALOG_URI=$(lk_jqr '.catalog_uri_private.value')
LAKEKEEPER_TOKEN_URI=$(lk_jqr '.token_uri_private.value')
LAKEKEEPER_CLIENT_ID=$(lk_jqr '.oidc_client_id.value')
LAKEKEEPER_CLIENT_SECRET=$(ssm "$LK_SSM/oauth2/client_secret")
LAKEKEEPER_WAREHOUSE=$(lk_jqr '.warehouse_name.value')
EOF
  echo "Lakekeeper block added to $ENVFILE (private-IP URIs). Set BENCH_CATALOG=lakekeeper to use it."
else
  echo "No lakekeeper-stack workspace '$ENV' — omitting the Lakekeeper block from $ENVFILE (run deploy/scripts/lakekeeper-up.sh $ENV first if you need it)."
fi

echo "Wrote $ENVFILE (EXASOL_HOST=$NODE1, namespace=$NS_TPCH). Run: make bench"
